name: societyease
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  flutter_staggered_animations: ^1.1.1
  intl: ^0.19.0
  fl_chart: ^0.68.0
  url_launcher: ^6.2.6

  path_provider: any
  open_file: any
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  open_file_macos: ^0.2.0




flutter:
  uses-material-design: true

  assets:
    - assets/images/

# âœ… This section must have NO indentation (be at the very left edge)
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.jpg"